### PR TITLE
Docs Add split (filter) as it's used in docs.

### PR DESCRIPTION
**Pull request by ajhunyady**

### CODE REVIEW

**Comment by ajhunyady** [comment]
@crajcan can you please help me merge this? It's likely due to changing the directory structure.

**Review by ajhunyady — COMMENTED** [review]
Thank you @crajcan

**Comment by crajcan** [comment]
> @crajcan can you please help me merge this? It's likely due to changing the directory structure.

It looks like you now have:

```
primitives
├── filter
├── filter-map
├── split
│   ├── filter
│   └── filter-map
└── ...
```
I assume you want to keep the old ones (primitives/filter and primitives/filter-map) ?


Also `primitives/split/filter/dataflow.yaml` is identical to `primtitives/split/filter-map/dataflow.yaml`.

**Comment by ajhunyady** [comment]
Yes, `primitive/filter` and `primitive/filter-map` stay. The new dataflow files should have been different. I'll correct that.

**Review by crajcan — APPROVED** [review]

**Pull request merged**
